# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Biddy Clone App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'MBProgressHUD', '~> 0.8'
  pod 'Reachability', '~> 3.1.1'
  pod 'TPKeyboardAvoiding', '~> 1.2'
  pod 'Alamofire' , '~> 4.9.1'
  pod 'SwiftyJSON'
  pod 'GoogleSignIn', '~> 5.0'
  pod 'Firebase/Core'
  pod 'Firebase/Crashlytics'
  pod 'Firebase/Analytics'
  pod 'FBSDKCoreKit', '~> 6.2'
  pod 'FBSDKGamingServicesKit', '~> 6.2'
  pod 'FBSDKLoginKit', '~> 6.2'
  pod 'FBSDKShareKit', '~> 6.2'

end

